### ISSUE TITLE
401 Unauthorized when clientId/clientSecret app authentication with GraphQL

### ISSUE THREAD

**Issue by gajus** [octokit/auth-oauth-app.js#46]
```js
const auth = createOAuthAppAuth({
  clientId: githubOauthApp.clientId,
  clientSecret: githubOauthApp.clientSecret,
});

const graphqlWithAuth = graphql.defaults({
  request: {
    hook: auth.hook,
  },
});

const response = await graphqlWithAuth(`query UserQuery {
  user(login: "gajus") {
    id
  }
}`);

```

Produces 401 response:

```json
{"message":"This endpoint requires you to be authenticated.","documentation_url":"https://developer.github.com/v3/#authentication"}

```

Expected behaviour is that I should be able to get public profile data.

Likely related to:

* https://github.com/octokit/auth-oauth-app.js/issues/44

**Comment by gr2m** [comment]
I think you cannot use the GraphQL API while authenticating as an OAuth App, you need to authenticate with an OAuth access token or an GitHub installation access token.

This is not related to #44.

I think it might be worth reaching out to https://support.github.com/contact and asking for the error message to be more helpful. It should say that OAuth App authentication is not permitted for GraphQL

**Comment by gajus** [comment]
This remains an active and a frustrating issue.

**Comment by gr2m** [comment]
There is nothing I can do on the SDK site here. You will have to create an OAuth access token in order to authenticate for GraphQL requests, you cannot authenticate using clientId/clientSecret alone. 

The same is true for the JWT Authentication for GitHub Apps, you cannot use that to authenticate for GraphQL requests, you have to create an installation access token.

I can just reiterate to get in touch with GitHub support, they will at least be able to explain why that is, I could only assume.

I'll close the issue because there is nothing actionable for me to act on here. I'm sorry, I wish I could be of better help

**Comment by Bruno-bot-stack** [comment]
> const auth = createOAuthAppAuth({
>   clientId: githubOauthApp.clientId,
>   clientSecret: githubOauthApp.clientSecret,
> });
> 
> const graphqlWithAuth = graphql.defaults({
>   request: {
>     hook: auth.hook,
>   },
> });
> 
> const response = await graphqlWithAuth(`query UserQuery {
>   user(login: "gajus") {
>     id
>   }
> }`);
> Produces 401 response:
> 
> {"message":"This endpoint requires you to be authenticated.","documentation_url":"https://developer.github.com/v3/#authentication"}
> Expected behaviour is that I should be able to get public profile data.
> 
> Likely related to:
> 
> * [bad_verification_code #44](https://github.com/octokit/auth-oauth-app.js/issues/44)

const auth = createOAuthAppAuth({
  clientId: githubOauthApp.clientId,
  clientSecret: githubOauthApp.clientSecret,
});

const graphqlWithAuth = graphql.defaults({
  request: {
    hook: auth.hook,
  },
});

const response = await graphqlWithAuth(`query UserQuery {
  user(login: "gajus") {
    id
  }
}`);
